        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 05 11:57:33 2018
        MODULE COMPVOLUMEINT__genmod
          INTERFACE 
            SUBROUTINE COMPVOLUMEINT
              USE GLOBAL
            END SUBROUTINE COMPVOLUMEINT
          END INTERFACE 
        END MODULE COMPVOLUMEINT__genmod
