        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 05 11:57:33 2018
        MODULE COMPPROJECTIONINT__genmod
          INTERFACE 
            SUBROUTINE COMPPROJECTIONINT(A,B,ID,P)
              INTEGER(KIND=4) :: A
              INTEGER(KIND=4) :: B
              INTEGER(KIND=4) :: ID
              REAL(KIND=16) :: P(10)
            END SUBROUTINE COMPPROJECTIONINT
          END INTERFACE 
        END MODULE COMPPROJECTIONINT__genmod
