        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 05 11:57:34 2018
        MODULE COTRANS__genmod
          INTERFACE 
            SUBROUTINE COTRANS
            END SUBROUTINE COTRANS
          END INTERFACE 
        END MODULE COTRANS__genmod
