        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 05 11:57:34 2018
        MODULE PREVARSOUT__genmod
          INTERFACE 
            SUBROUTINE PREVARSOUT
            END SUBROUTINE PREVARSOUT
          END INTERFACE 
        END MODULE PREVARSOUT__genmod
