        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 05 11:57:33 2018
        MODULE VARSOUT__genmod
          INTERFACE 
            SUBROUTINE VARSOUT
            END SUBROUTINE VARSOUT
          END INTERFACE 
        END MODULE VARSOUT__genmod
