        !COMPILER-GENERATED INTERFACE MODULE: Mon Nov 05 11:57:34 2018
        MODULE VFDATAOUT__genmod
          INTERFACE 
            SUBROUTINE VFDATAOUT
            END SUBROUTINE VFDATAOUT
          END INTERFACE 
        END MODULE VFDATAOUT__genmod
