        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:30 2019
        MODULE ATTITUDE__genmod
          INTERFACE 
            SUBROUTINE ATTITUDE
            END SUBROUTINE ATTITUDE
          END INTERFACE 
        END MODULE ATTITUDE__genmod
