        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:35 2019
        MODULE ATTITUDE__genmod
          INTERFACE 
            SUBROUTINE ATTITUDE
            END SUBROUTINE ATTITUDE
          END INTERFACE 
        END MODULE ATTITUDE__genmod
