        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:51 2018
        MODULE ATTITUDEGRAVBODY__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEGRAVBODY
            END SUBROUTINE ATTITUDEGRAVBODY
          END INTERFACE 
        END MODULE ATTITUDEGRAVBODY__genmod
