        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:51 2018
        MODULE ATTITUDEBONDEDWALLSQM__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEBONDEDWALLSQM
            END SUBROUTINE ATTITUDEBONDEDWALLSQM
          END INTERFACE 
        END MODULE ATTITUDEBONDEDWALLSQM__genmod
