        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 05 01:33:13 2018
        MODULE ATTITUDEBONDEDWALLSQM__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEBONDEDWALLSQM
            END SUBROUTINE ATTITUDEBONDEDWALLSQM
          END INTERFACE 
        END MODULE ATTITUDEBONDEDWALLSQM__genmod
