        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 05 01:33:14 2018
        MODULE ATTITUDEBONDEDWALLS__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEBONDEDWALLS
            END SUBROUTINE ATTITUDEBONDEDWALLS
          END INTERFACE 
        END MODULE ATTITUDEBONDEDWALLS__genmod
