        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:49 2018
        MODULE ATTITUDE__genmod
          INTERFACE 
            SUBROUTINE ATTITUDE
            END SUBROUTINE ATTITUDE
          END INTERFACE 
        END MODULE ATTITUDE__genmod
