        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:11 2018
        MODULE ATTITUDEGRAVBODY__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEGRAVBODY
            END SUBROUTINE ATTITUDEGRAVBODY
          END INTERFACE 
        END MODULE ATTITUDEGRAVBODY__genmod
