        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:52 2018
        MODULE ATTITUDEBONDEDWALLS__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEBONDEDWALLS
            END SUBROUTINE ATTITUDEBONDEDWALLS
          END INTERFACE 
        END MODULE ATTITUDEBONDEDWALLS__genmod
