        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:09 2018
        MODULE ATTITUDEBONDEDWALLS__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEBONDEDWALLS
            END SUBROUTINE ATTITUDEBONDEDWALLS
          END INTERFACE 
        END MODULE ATTITUDEBONDEDWALLS__genmod
