        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:08 2018
        MODULE ATTITUDEBONDEDWALLSQM__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEBONDEDWALLSQM
            END SUBROUTINE ATTITUDEBONDEDWALLSQM
          END INTERFACE 
        END MODULE ATTITUDEBONDEDWALLSQM__genmod
