        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:01 2019
        MODULE ATTITUDEQ2M__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEQ2M(T_QUATERNION,T_MATI,T_MATB)
              REAL(KIND=8) :: T_QUATERNION(4)
              REAL(KIND=8) :: T_MATI(3,3)
              REAL(KIND=8) :: T_MATB(3,3)
            END SUBROUTINE ATTITUDEQ2M
          END INTERFACE 
        END MODULE ATTITUDEQ2M__genmod
