        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 05 01:33:13 2018
        MODULE ATTITUDEGRAVBODY__genmod
          INTERFACE 
            SUBROUTINE ATTITUDEGRAVBODY
            END SUBROUTINE ATTITUDEGRAVBODY
          END INTERFACE 
        END MODULE ATTITUDEGRAVBODY__genmod
