        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:05 2019
        MODULE FORCEBIDISPERSEMIRROR__genmod
          INTERFACE 
            SUBROUTINE FORCEBIDISPERSEMIRROR
            END SUBROUTINE FORCEBIDISPERSEMIRROR
          END INTERFACE 
        END MODULE FORCEBIDISPERSEMIRROR__genmod
