        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:12 2019
        MODULE FORCEFUNNELWALLS__genmod
          INTERFACE 
            SUBROUTINE FORCEFUNNELWALLS
            END SUBROUTINE FORCEFUNNELWALLS
          END INTERFACE 
        END MODULE FORCEFUNNELWALLS__genmod
