        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 05 01:33:14 2018
        MODULE FORCEFUNNELWALLS__genmod
          INTERFACE 
            SUBROUTINE FORCEFUNNELWALLS
            END SUBROUTINE FORCEFUNNELWALLS
          END INTERFACE 
        END MODULE FORCEFUNNELWALLS__genmod
