        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:36 2019
        MODULE INITIALBIDISPERSE__genmod
          INTERFACE 
            SUBROUTINE INITIALBIDISPERSE
            END SUBROUTINE INITIALBIDISPERSE
          END INTERFACE 
        END MODULE INITIALBIDISPERSE__genmod
