        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:32 2019
        MODULE INITIALLATTICE__genmod
          INTERFACE 
            SUBROUTINE INITIALLATTICE
            END SUBROUTINE INITIALLATTICE
          END INTERFACE 
        END MODULE INITIALLATTICE__genmod
