        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:04 2019
        MODULE INITIALLATTICE__genmod
          INTERFACE 
            SUBROUTINE INITIALLATTICE
            END SUBROUTINE INITIALLATTICE
          END INTERFACE 
        END MODULE INITIALLATTICE__genmod
