        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:30 2019
        MODULE INITIALTRIMESH__genmod
          INTERFACE 
            SUBROUTINE INITIALTRIMESH
            END SUBROUTINE INITIALTRIMESH
          END INTERFACE 
        END MODULE INITIALTRIMESH__genmod
