        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:33 2019
        MODULE INITIALASSEMBLY__genmod
          INTERFACE 
            SUBROUTINE INITIALASSEMBLY
            END SUBROUTINE INITIALASSEMBLY
          END INTERFACE 
        END MODULE INITIALASSEMBLY__genmod
