        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:14 2019
        MODULE INITIALSYSTEM__genmod
          INTERFACE 
            SUBROUTINE INITIALSYSTEM
            END SUBROUTINE INITIALSYSTEM
          END INTERFACE 
        END MODULE INITIALSYSTEM__genmod
