        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:38 2019
        MODULE INITIALTRIMESH__genmod
          INTERFACE 
            SUBROUTINE INITIALTRIMESH
            END SUBROUTINE INITIALTRIMESH
          END INTERFACE 
        END MODULE INITIALTRIMESH__genmod
