        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:15 2019
        MODULE INITIALLATTICE__genmod
          INTERFACE 
            SUBROUTINE INITIALLATTICE
            END SUBROUTINE INITIALLATTICE
          END INTERFACE 
        END MODULE INITIALLATTICE__genmod
