        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:01 2019
        MODULE INITIALTRIMESH__genmod
          INTERFACE 
            SUBROUTINE INITIALTRIMESH
            END SUBROUTINE INITIALTRIMESH
          END INTERFACE 
        END MODULE INITIALTRIMESH__genmod
