        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:16 2019
        MODULE INITIALASSEMBLY__genmod
          INTERFACE 
            SUBROUTINE INITIALASSEMBLY
            END SUBROUTINE INITIALASSEMBLY
          END INTERFACE 
        END MODULE INITIALASSEMBLY__genmod
