        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:33 2019
        MODULE INITIALSYSTEM__genmod
          INTERFACE 
            SUBROUTINE INITIALSYSTEM
            END SUBROUTINE INITIALSYSTEM
          END INTERFACE 
        END MODULE INITIALSYSTEM__genmod
