        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:05 2019
        MODULE INITIALBIDISPERSE__genmod
          INTERFACE 
            SUBROUTINE INITIALBIDISPERSE
            END SUBROUTINE INITIALBIDISPERSE
          END INTERFACE 
        END MODULE INITIALBIDISPERSE__genmod
