        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 05 01:33:13 2018
        MODULE INITIALSYSTEM__genmod
          INTERFACE 
            SUBROUTINE INITIALSYSTEM
            END SUBROUTINE INITIALSYSTEM
          END INTERFACE 
        END MODULE INITIALSYSTEM__genmod
