        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:11 2018
        MODULE INTGRT__genmod
          INTERFACE 
            SUBROUTINE INTGRT
            END SUBROUTINE INTGRT
          END INTERFACE 
        END MODULE INTGRT__genmod
