        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:29 2019
        MODULE INTGRT__genmod
          INTERFACE 
            SUBROUTINE INTGRT
            END SUBROUTINE INTGRT
          END INTERFACE 
        END MODULE INTGRT__genmod
