        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:31 2019
        MODULE INTGRTSPHEREBODY__genmod
          INTERFACE 
            SUBROUTINE INTGRTSPHEREBODY
            END SUBROUTINE INTGRTSPHEREBODY
          END INTERFACE 
        END MODULE INTGRTSPHEREBODY__genmod
