        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:05 2019
        MODULE INTGRTBIDISPERSE__genmod
          INTERFACE 
            SUBROUTINE INTGRTBIDISPERSE
            END SUBROUTINE INTGRTBIDISPERSE
          END INTERFACE 
        END MODULE INTGRTBIDISPERSE__genmod
