        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:38 2019
        MODULE INTGRTBIDISPERSE__genmod
          INTERFACE 
            SUBROUTINE INTGRTBIDISPERSE
            END SUBROUTINE INTGRTBIDISPERSE
          END INTERFACE 
        END MODULE INTGRTBIDISPERSE__genmod
