        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:02 2019
        MODULE INTGRTSPHEREBODY__genmod
          INTERFACE 
            SUBROUTINE INTGRTSPHEREBODY
            END SUBROUTINE INTGRTSPHEREBODY
          END INTERFACE 
        END MODULE INTGRTSPHEREBODY__genmod
