        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:12 2019
        MODULE INTGRT__genmod
          INTERFACE 
            SUBROUTINE INTGRT
            END SUBROUTINE INTGRT
          END INTERFACE 
        END MODULE INTGRT__genmod
