        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:34 2019
        MODULE INTGRTSPHEREBODY__genmod
          INTERFACE 
            SUBROUTINE INTGRTSPHEREBODY
            END SUBROUTINE INTGRTSPHEREBODY
          END INTERFACE 
        END MODULE INTGRTSPHEREBODY__genmod
