        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:16 2019
        MODULE INTGRTASSEMBLY__genmod
          INTERFACE 
            SUBROUTINE INTGRTASSEMBLY
            END SUBROUTINE INTGRTASSEMBLY
          END INTERFACE 
        END MODULE INTGRTASSEMBLY__genmod
