        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:33 2019
        MODULE INTGRTASSEMBLY__genmod
          INTERFACE 
            SUBROUTINE INTGRTASSEMBLY
            END SUBROUTINE INTGRTASSEMBLY
          END INTERFACE 
        END MODULE INTGRTASSEMBLY__genmod
