        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:31 2019
        MODULE INTGRTGRAVBODY__genmod
          INTERFACE 
            SUBROUTINE INTGRTGRAVBODY
            END SUBROUTINE INTGRTGRAVBODY
          END INTERFACE 
        END MODULE INTGRTGRAVBODY__genmod
