        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:03 2019
        MODULE INTGRTGRAVBODY__genmod
          INTERFACE 
            SUBROUTINE INTGRTGRAVBODY
            END SUBROUTINE INTGRTGRAVBODY
          END INTERFACE 
        END MODULE INTGRTGRAVBODY__genmod
