        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:07 2019
        MODULE LATTICEGENERATEBIDISPERSE__genmod
          INTERFACE 
            SUBROUTINE LATTICEGENERATEBIDISPERSE
            END SUBROUTINE LATTICEGENERATEBIDISPERSE
          END INTERFACE 
        END MODULE LATTICEGENERATEBIDISPERSE__genmod
