        !COMPILER-GENERATED INTERFACE MODULE: Wed May 29 21:05:13 2019
        MODULE LATTICEGENERATE__genmod
          INTERFACE 
            SUBROUTINE LATTICEGENERATE
            END SUBROUTINE LATTICEGENERATE
          END INTERFACE 
        END MODULE LATTICEGENERATE__genmod
