        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:38 2019
        MODULE LATTICEGENERATEBIDISPERSE__genmod
          INTERFACE 
            SUBROUTINE LATTICEGENERATEBIDISPERSE
            END SUBROUTINE LATTICEGENERATEBIDISPERSE
          END INTERFACE 
        END MODULE LATTICEGENERATEBIDISPERSE__genmod
