        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:33 2019
        MODULE LATTICEGENERATE__genmod
          INTERFACE 
            SUBROUTINE LATTICEGENERATE
            END SUBROUTINE LATTICEGENERATE
          END INTERFACE 
        END MODULE LATTICEGENERATE__genmod
