        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:52 2018
        MODULE LATTICEGENERATE__genmod
          INTERFACE 
            SUBROUTINE LATTICEGENERATE
            END SUBROUTINE LATTICEGENERATE
          END INTERFACE 
        END MODULE LATTICEGENERATE__genmod
