        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:09 2018
        MODULE LOADDATA__genmod
          INTERFACE 
            SUBROUTINE LOADDATA
            END SUBROUTINE LOADDATA
          END INTERFACE 
        END MODULE LOADDATA__genmod
