        !COMPILER-GENERATED INTERFACE MODULE: Fri Oct 05 01:33:12 2018
        MODULE LOADDATA__genmod
          INTERFACE 
            SUBROUTINE LOADDATA
            END SUBROUTINE LOADDATA
          END INTERFACE 
        END MODULE LOADDATA__genmod
