        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:51 2018
        MODULE LOADDATA__genmod
          INTERFACE 
            SUBROUTINE LOADDATA
            END SUBROUTINE LOADDATA
          END INTERFACE 
        END MODULE LOADDATA__genmod
