        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:10 2018
        MODULE OUTPUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT
            END SUBROUTINE OUTPUT
          END INTERFACE 
        END MODULE OUTPUT__genmod
