        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:08 2019
        MODULE OUTPUT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT
            END SUBROUTINE OUTPUT
          END INTERFACE 
        END MODULE OUTPUT__genmod
