        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:10 2018
        MODULE PERIODIC__genmod
          INTERFACE 
            SUBROUTINE PERIODIC
            END SUBROUTINE PERIODIC
          END INTERFACE 
        END MODULE PERIODIC__genmod
