        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 22 19:19:52 2018
        MODULE PERIODIC__genmod
          INTERFACE 
            SUBROUTINE PERIODIC
            END SUBROUTINE PERIODIC
          END INTERFACE 
        END MODULE PERIODIC__genmod
