        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 15 23:37:06 2019
        MODULE PERIODIC__genmod
          INTERFACE 
            SUBROUTINE PERIODIC
            END SUBROUTINE PERIODIC
          END INTERFACE 
        END MODULE PERIODIC__genmod
