        !COMPILER-GENERATED INTERFACE MODULE: Mon Oct 29 22:10:09 2018
        MODULE PLANET__genmod
          INTERFACE 
            SUBROUTINE PLANET
            END SUBROUTINE PLANET
          END INTERFACE 
        END MODULE PLANET__genmod
