        !COMPILER-GENERATED INTERFACE MODULE: Sun Mar 17 23:06:35 2019
        MODULE START__genmod
          INTERFACE 
            SUBROUTINE START
            END SUBROUTINE START
          END INTERFACE 
        END MODULE START__genmod
