        !COMPILER-GENERATED INTERFACE MODULE: Tue Jun 11 15:23:30 2019
        MODULE START__genmod
          INTERFACE 
            SUBROUTINE START
            END SUBROUTINE START
          END INTERFACE 
        END MODULE START__genmod
